/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Тип оборудования для инвалидов. Справочное значение
    /// </summary>
    /// <value>Тип оборудования для инвалидов. Справочное значение</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum AccessibilityCode
    {
        /// <summary>
        /// Enum Braille for value: Braille | Шрифт Брайля
        /// </summary>
        [EnumMember(Value = "Braille | Шрифт Брайля")]
        Braille = 1,
        /// <summary>
        /// Enum AudioCashMachine for value: AudioCashMachine | Голосовое озвучивание
        /// </summary>
        [EnumMember(Value = "AudioCashMachine | Голосовое озвучивание")]
        AudioCashMachine = 2,
        /// <summary>
        /// Enum AutomaticDoors for value: AutomaticDoors | Автоматические двери
        /// </summary>
        [EnumMember(Value = "AutomaticDoors | Автоматические двери")]
        AutomaticDoors = 3,
        /// <summary>
        /// Enum WheelchairAccess for value: WheelchairAccess | Доступность для инвалидных колясок
        /// </summary>
        [EnumMember(Value = "WheelchairAccess | Доступность для инвалидных колясок")]
        WheelchairAccess = 4,
        /// <summary>
        /// Enum ExternalRamp for value: ExternalRamp | Внешний пандус
        /// </summary>
        [EnumMember(Value = "ExternalRamp | Внешний пандус")]
        ExternalRamp = 5,
        /// <summary>
        /// Enum InternalRamp for value: InternalRamp | Внутренний пандус
        /// </summary>
        [EnumMember(Value = "InternalRamp | Внутренний пандус")]
        InternalRamp = 6,
        /// <summary>
        /// Enum Other for value: Other | Другие
        /// </summary>
        [EnumMember(Value = "Other | Другие")]
        Other = 7    }
}
