/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Схема погашения кредитного продукта (Аннуитет, Платежи равными долями, Дифференцированный платеж)
    /// </summary>
    /// <value>Схема погашения кредитного продукта (Аннуитет, Платежи равными долями, Дифференцированный платеж)</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum AmountTypeCode
    {
        /// <summary>
        /// Enum Balloon for value: Balloon  | Погашение по графику единовременных выплат в определенный момент срока
        /// </summary>
        [EnumMember(Value = "Balloon  | Погашение по графику единовременных выплат в определенный момент срока")]
        Balloon = 1,
        /// <summary>
        /// Enum BalanceToDate for value: BalanceToDate | Весь оставшийся остаток по кредиту, включая проценты, комиссионные и сборы
        /// </summary>
        [EnumMember(Value = "BalanceToDate | Весь оставшийся остаток по кредиту, включая проценты, комиссионные и сборы")]
        BalanceToDate = 2,
        /// <summary>
        /// Enum CapitalAndInterest for value: CapitalAndInterest  | Погашение включает капитал, проценты и комиссионные сборы
        /// </summary>
        [EnumMember(Value = "CapitalAndInterest  | Погашение включает капитал, проценты и комиссионные сборы")]
        CapitalAndInterest = 3,
        /// <summary>
        /// Enum FeeChargeCap for value: FeeChargeCap  | Погашение включает только комиссии и сборы
        /// </summary>
        [EnumMember(Value = "FeeChargeCap  | Погашение включает только комиссии и сборы")]
        FeeChargeCap = 4,
        /// <summary>
        /// Enum InterestOnly for value: InterestOnly  | Погашение включает проценты и комиссионные сборы
        /// </summary>
        [EnumMember(Value = "InterestOnly  | Погашение включает проценты и комиссионные сборы")]
        InterestOnly = 5,
        /// <summary>
        /// Enum Bullet for value: Bullet  | Погашение по концу срока
        /// </summary>
        [EnumMember(Value = "Bullet  | Погашение по концу срока")]
        Bullet = 6,
        /// <summary>
        /// Enum Other for value: Other  | Другой тип погашения
        /// </summary>
        [EnumMember(Value = "Other  | Другой тип погашения")]
        Other = 7    }
}
