/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Услуги отделения кредитной организации
    /// </summary>
    [DataContract]
        public partial class BranchServices :  IEquatable<BranchServices>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BranchServices" /> class.
        /// </summary>
        /// <param name="service">service (required).</param>
        /// <param name="currencyExchange">Подробная информация об обмене валюты.</param>
        public BranchServices(List<BranchService> service = default(List<BranchService>), List<CurrencyExchange> currencyExchange = default(List<CurrencyExchange>))
        {
            // to ensure "service" is required (not null)
            if (service == null)
            {
                throw new InvalidDataException("service is a required property for BranchServices and cannot be null");
            }
            else
            {
                this.Service = service;
            }
            this.CurrencyExchange = currencyExchange;
        }
        
        /// <summary>
        /// Gets or Sets Service
        /// </summary>
        [DataMember(Name="Service", EmitDefaultValue=false)]
        public List<BranchService> Service { get; set; }

        /// <summary>
        /// Подробная информация об обмене валюты
        /// </summary>
        /// <value>Подробная информация об обмене валюты</value>
        [DataMember(Name="CurrencyExchange", EmitDefaultValue=false)]
        public List<CurrencyExchange> CurrencyExchange { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BranchServices {\n");
            sb.Append("  Service: ").Append(Service).Append("\n");
            sb.Append("  CurrencyExchange: ").Append(CurrencyExchange).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BranchServices);
        }

        /// <summary>
        /// Returns true if BranchServices instances are equal
        /// </summary>
        /// <param name="input">Instance of BranchServices to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BranchServices input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Service == input.Service ||
                    this.Service != null &&
                    input.Service != null &&
                    this.Service.SequenceEqual(input.Service)
                ) && 
                (
                    this.CurrencyExchange == input.CurrencyExchange ||
                    this.CurrencyExchange != null &&
                    input.CurrencyExchange != null &&
                    this.CurrencyExchange.SequenceEqual(input.CurrencyExchange)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Service != null)
                    hashCode = hashCode * 59 + this.Service.GetHashCode();
                if (this.CurrencyExchange != null)
                    hashCode = hashCode * 59 + this.CurrencyExchange.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
