/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Наименование схемы карты
    /// </summary>
    /// <value>Наименование схемы карты</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum CardSchemeNameCode
    {
        /// <summary>
        /// Enum AmericanExpress for value: AmericanExpress | Международная платежная система
        /// </summary>
        [EnumMember(Value = "AmericanExpress | Международная платежная система")]
        AmericanExpress = 1,
        /// <summary>
        /// Enum Diners for value: Diners | Международная платежная система
        /// </summary>
        [EnumMember(Value = "Diners | Международная платежная система")]
        Diners = 2,
        /// <summary>
        /// Enum Discover for value: Discover | Международная платежная система
        /// </summary>
        [EnumMember(Value = "Discover | Международная платежная система")]
        Discover = 3,
        /// <summary>
        /// Enum MasterCard for value: MasterCard | Международная платежная система
        /// </summary>
        [EnumMember(Value = "MasterCard | Международная платежная система")]
        MasterCard = 4,
        /// <summary>
        /// Enum VISA for value: VISA | Международная платежная система
        /// </summary>
        [EnumMember(Value = "VISA | Международная платежная система")]
        VISA = 5,
        /// <summary>
        /// Enum MIR for value: MIR | Российская национальная платежная система
        /// </summary>
        [EnumMember(Value = "MIR | Российская национальная платежная система")]
        MIR = 6,
        /// <summary>
        /// Enum ArCa for value: ArCa | Армянская национальная платежная система
        /// </summary>
        [EnumMember(Value = "ArCa | Армянская национальная платежная система")]
        ArCa = 7,
        /// <summary>
        /// Enum BELKART for value: BELKART | Белорусская национальная платежная система
        /// </summary>
        [EnumMember(Value = "BELKART | Белорусская национальная платежная система")]
        BELKART = 8,
        /// <summary>
        /// Enum ELCART for value: ELCART | Киргизская национальная платежная система
        /// </summary>
        [EnumMember(Value = "ELCART | Киргизская национальная платежная система")]
        ELCART = 9,
        /// <summary>
        /// Enum JCB for value: JCB | Платежная система Японии
        /// </summary>
        [EnumMember(Value = "JCB | Платежная система Японии")]
        JCB = 10,
        /// <summary>
        /// Enum UnionPay for value: UnionPay | Национальная платежная система Китая
        /// </summary>
        [EnumMember(Value = "UnionPay | Национальная платежная система Китая")]
        UnionPay = 11    }
}
