/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Подробная информация о процентных ставках для дебетовых продуктов
    /// </summary>
    [DataContract]
        public partial class CreditInterest :  IEquatable<CreditInterest>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CreditInterest" /> class.
        /// </summary>
        /// <param name="comments">comments.</param>
        /// <param name="tierBandSet">Группа описания начисления процентов (required).</param>
        public CreditInterest(Comments comments = default(Comments), List<TierBandSet> tierBandSet = default(List<TierBandSet>))
        {
            // to ensure "tierBandSet" is required (not null)
            if (tierBandSet == null)
            {
                throw new InvalidDataException("tierBandSet is a required property for CreditInterest and cannot be null");
            }
            else
            {
                this.TierBandSet = tierBandSet;
            }
            this.Comments = comments;
        }
        
        /// <summary>
        /// Gets or Sets Comments
        /// </summary>
        [DataMember(Name="comments", EmitDefaultValue=false)]
        public Comments Comments { get; set; }

        /// <summary>
        /// Группа описания начисления процентов
        /// </summary>
        /// <value>Группа описания начисления процентов</value>
        [DataMember(Name="TierBandSet", EmitDefaultValue=false)]
        public List<TierBandSet> TierBandSet { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CreditInterest {\n");
            sb.Append("  Comments: ").Append(Comments).Append("\n");
            sb.Append("  TierBandSet: ").Append(TierBandSet).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CreditInterest);
        }

        /// <summary>
        /// Returns true if CreditInterest instances are equal
        /// </summary>
        /// <param name="input">Instance of CreditInterest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CreditInterest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Comments == input.Comments ||
                    (this.Comments != null &&
                    this.Comments.Equals(input.Comments))
                ) && 
                (
                    this.TierBandSet == input.TierBandSet ||
                    this.TierBandSet != null &&
                    input.TierBandSet != null &&
                    this.TierBandSet.SequenceEqual(input.TierBandSet)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Comments != null)
                    hashCode = hashCode * 59 + this.Comments.GetHashCode();
                if (this.TierBandSet != null)
                    hashCode = hashCode * 59 + this.TierBandSet.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
