/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Раздел данных ответа информации об устройствах
    /// </summary>
    [DataContract]
        public partial class DataDeviceResponse :  IEquatable<DataDeviceResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DataDeviceResponse" /> class.
        /// </summary>
        /// <param name="device">Комплексный объект банкомат или устройство.</param>
        public DataDeviceResponse(List<Device> device = default(List<Device>))
        {
            this.Device = device;
        }
        
        /// <summary>
        /// Комплексный объект банкомат или устройство
        /// </summary>
        /// <value>Комплексный объект банкомат или устройство</value>
        [DataMember(Name="Device", EmitDefaultValue=false)]
        public List<Device> Device { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DataDeviceResponse {\n");
            sb.Append("  Device: ").Append(Device).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DataDeviceResponse);
        }

        /// <summary>
        /// Returns true if DataDeviceResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of DataDeviceResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DataDeviceResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Device == input.Device ||
                    this.Device != null &&
                    input.Device != null &&
                    this.Device.SequenceEqual(input.Device)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Device != null)
                    hashCode = hashCode * 59 + this.Device.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
