/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Группа уровней или диапазонов процентной ставки для выплат по кредиту
    /// </summary>
    [DataContract]
        public partial class DebitInterestTierBandSet :  IEquatable<DebitInterestTierBandSet>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DebitInterestTierBandSet" /> class.
        /// </summary>
        /// <param name="identification">Идентификатор группы уровня процентной ставки.</param>
        /// <param name="tierBandMethod">tierBandMethod (required).</param>
        /// <param name="calculationMethod">calculationMethod (required).</param>
        /// <param name="comments">comments.</param>
        /// <param name="debitInterestTierBand">Подробная информация о процентной ставке по кредиту (required).</param>
        /// <param name="tierBandSetEligibility">Ограничения на группу начисления процентов.</param>
        /// <param name="interestFeesCharges">Информация о комиссиях и сборах, которые связаны со всей группой уровня процентной ставки.</param>
        public DebitInterestTierBandSet(string identification = default(string), TierBandMethod tierBandMethod = default(TierBandMethod), InterestCalculationMethod calculationMethod = default(InterestCalculationMethod), Comments comments = default(Comments), List<DebitInterestTierBand> debitInterestTierBand = default(List<DebitInterestTierBand>), List<Eligibility> tierBandSetEligibility = default(List<Eligibility>), List<InterestFeesCharges> interestFeesCharges = default(List<InterestFeesCharges>))
        {
            // to ensure "tierBandMethod" is required (not null)
            if (tierBandMethod == null)
            {
                throw new InvalidDataException("tierBandMethod is a required property for DebitInterestTierBandSet and cannot be null");
            }
            else
            {
                this.TierBandMethod = tierBandMethod;
            }
            // to ensure "calculationMethod" is required (not null)
            if (calculationMethod == null)
            {
                throw new InvalidDataException("calculationMethod is a required property for DebitInterestTierBandSet and cannot be null");
            }
            else
            {
                this.CalculationMethod = calculationMethod;
            }
            // to ensure "debitInterestTierBand" is required (not null)
            if (debitInterestTierBand == null)
            {
                throw new InvalidDataException("debitInterestTierBand is a required property for DebitInterestTierBandSet and cannot be null");
            }
            else
            {
                this.DebitInterestTierBand = debitInterestTierBand;
            }
            this.Identification = identification;
            this.Comments = comments;
            this.TierBandSetEligibility = tierBandSetEligibility;
            this.InterestFeesCharges = interestFeesCharges;
        }
        
        /// <summary>
        /// Идентификатор группы уровня процентной ставки
        /// </summary>
        /// <value>Идентификатор группы уровня процентной ставки</value>
        [DataMember(Name="identification", EmitDefaultValue=false)]
        public string Identification { get; set; }

        /// <summary>
        /// Gets or Sets TierBandMethod
        /// </summary>
        [DataMember(Name="tierBandMethod", EmitDefaultValue=false)]
        public TierBandMethod TierBandMethod { get; set; }

        /// <summary>
        /// Gets or Sets CalculationMethod
        /// </summary>
        [DataMember(Name="calculationMethod", EmitDefaultValue=false)]
        public InterestCalculationMethod CalculationMethod { get; set; }

        /// <summary>
        /// Gets or Sets Comments
        /// </summary>
        [DataMember(Name="comments", EmitDefaultValue=false)]
        public Comments Comments { get; set; }

        /// <summary>
        /// Подробная информация о процентной ставке по кредиту
        /// </summary>
        /// <value>Подробная информация о процентной ставке по кредиту</value>
        [DataMember(Name="DebitInterestTierBand", EmitDefaultValue=false)]
        public List<DebitInterestTierBand> DebitInterestTierBand { get; set; }

        /// <summary>
        /// Ограничения на группу начисления процентов
        /// </summary>
        /// <value>Ограничения на группу начисления процентов</value>
        [DataMember(Name="TierBandSetEligibility", EmitDefaultValue=false)]
        public List<Eligibility> TierBandSetEligibility { get; set; }

        /// <summary>
        /// Информация о комиссиях и сборах, которые связаны со всей группой уровня процентной ставки
        /// </summary>
        /// <value>Информация о комиссиях и сборах, которые связаны со всей группой уровня процентной ставки</value>
        [DataMember(Name="InterestFeesCharges", EmitDefaultValue=false)]
        public List<InterestFeesCharges> InterestFeesCharges { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DebitInterestTierBandSet {\n");
            sb.Append("  Identification: ").Append(Identification).Append("\n");
            sb.Append("  TierBandMethod: ").Append(TierBandMethod).Append("\n");
            sb.Append("  CalculationMethod: ").Append(CalculationMethod).Append("\n");
            sb.Append("  Comments: ").Append(Comments).Append("\n");
            sb.Append("  DebitInterestTierBand: ").Append(DebitInterestTierBand).Append("\n");
            sb.Append("  TierBandSetEligibility: ").Append(TierBandSetEligibility).Append("\n");
            sb.Append("  InterestFeesCharges: ").Append(InterestFeesCharges).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DebitInterestTierBandSet);
        }

        /// <summary>
        /// Returns true if DebitInterestTierBandSet instances are equal
        /// </summary>
        /// <param name="input">Instance of DebitInterestTierBandSet to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DebitInterestTierBandSet input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Identification == input.Identification ||
                    (this.Identification != null &&
                    this.Identification.Equals(input.Identification))
                ) && 
                (
                    this.TierBandMethod == input.TierBandMethod ||
                    (this.TierBandMethod != null &&
                    this.TierBandMethod.Equals(input.TierBandMethod))
                ) && 
                (
                    this.CalculationMethod == input.CalculationMethod ||
                    (this.CalculationMethod != null &&
                    this.CalculationMethod.Equals(input.CalculationMethod))
                ) && 
                (
                    this.Comments == input.Comments ||
                    (this.Comments != null &&
                    this.Comments.Equals(input.Comments))
                ) && 
                (
                    this.DebitInterestTierBand == input.DebitInterestTierBand ||
                    this.DebitInterestTierBand != null &&
                    input.DebitInterestTierBand != null &&
                    this.DebitInterestTierBand.SequenceEqual(input.DebitInterestTierBand)
                ) && 
                (
                    this.TierBandSetEligibility == input.TierBandSetEligibility ||
                    this.TierBandSetEligibility != null &&
                    input.TierBandSetEligibility != null &&
                    this.TierBandSetEligibility.SequenceEqual(input.TierBandSetEligibility)
                ) && 
                (
                    this.InterestFeesCharges == input.InterestFeesCharges ||
                    this.InterestFeesCharges != null &&
                    input.InterestFeesCharges != null &&
                    this.InterestFeesCharges.SequenceEqual(input.InterestFeesCharges)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Identification != null)
                    hashCode = hashCode * 59 + this.Identification.GetHashCode();
                if (this.TierBandMethod != null)
                    hashCode = hashCode * 59 + this.TierBandMethod.GetHashCode();
                if (this.CalculationMethod != null)
                    hashCode = hashCode * 59 + this.CalculationMethod.GetHashCode();
                if (this.Comments != null)
                    hashCode = hashCode * 59 + this.Comments.GetHashCode();
                if (this.DebitInterestTierBand != null)
                    hashCode = hashCode * 59 + this.DebitInterestTierBand.GetHashCode();
                if (this.TierBandSetEligibility != null)
                    hashCode = hashCode * 59 + this.TierBandSetEligibility.GetHashCode();
                if (this.InterestFeesCharges != null)
                    hashCode = hashCode * 59 + this.InterestFeesCharges.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
