/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Подробная информация о процентной ставке по кредиту
    /// </summary>
    [DataContract]
        public partial class DebitInterestTierBand :  IEquatable<DebitInterestTierBand>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DebitInterestTierBand" /> class.
        /// </summary>
        /// <param name="aER">aER (required).</param>
        /// <param name="comments">comments.</param>
        /// <param name="identification">Уникальное определение диапазона уровней процентной ставки для кредита.</param>
        /// <param name="tierCurrency">Валюта уровня.</param>
        /// <param name="tierValueMinimum">tierValueMinimum (required).</param>
        /// <param name="tierValueMaximum">tierValueMaximum.</param>
        /// <param name="tierValueMinTerm">Минимальный срок, на которой применяется уровень процентной ставки (required).</param>
        /// <param name="minTermPeriod">minTermPeriod (required).</param>
        /// <param name="tierValueMaxTerm">Максимальный срок, для которой применяется уровень процентной ставки.</param>
        /// <param name="maxTermPeriod">maxTermPeriod.</param>
        /// <param name="interestRate">interestRate.</param>
        /// <param name="interestRateType">interestRateType.</param>
        /// <param name="interestFeesCharges">Информация о комиссиях и сборах.</param>
        public DebitInterestTierBand(string aER = default(string), Comments comments = default(Comments), string identification = default(string),  tierCurrency = default(), string tierValueMinimum = default(string), string tierValueMaximum = default(string), int? tierValueMinTerm = default(int?), PeriodUnit minTermPeriod = default(PeriodUnit), int? tierValueMaxTerm = default(int?), PeriodUnit maxTermPeriod = default(PeriodUnit), string interestRate = default(string), InterestRateType interestRateType = default(InterestRateType), List<InterestFeesCharges> interestFeesCharges = default(List<InterestFeesCharges>))
        {
            // to ensure "aER" is required (not null)
            if (aER == null)
            {
                throw new InvalidDataException("aER is a required property for DebitInterestTierBand and cannot be null");
            }
            else
            {
                this.AER = aER;
            }
            // to ensure "tierValueMinimum" is required (not null)
            if (tierValueMinimum == null)
            {
                throw new InvalidDataException("tierValueMinimum is a required property for DebitInterestTierBand and cannot be null");
            }
            else
            {
                this.TierValueMinimum = tierValueMinimum;
            }
            // to ensure "tierValueMinTerm" is required (not null)
            if (tierValueMinTerm == null)
            {
                throw new InvalidDataException("tierValueMinTerm is a required property for DebitInterestTierBand and cannot be null");
            }
            else
            {
                this.TierValueMinTerm = tierValueMinTerm;
            }
            // to ensure "minTermPeriod" is required (not null)
            if (minTermPeriod == null)
            {
                throw new InvalidDataException("minTermPeriod is a required property for DebitInterestTierBand and cannot be null");
            }
            else
            {
                this.MinTermPeriod = minTermPeriod;
            }
            this.Comments = comments;
            this.Identification = identification;
            this.TierCurrency = tierCurrency;
            this.TierValueMaximum = tierValueMaximum;
            this.TierValueMaxTerm = tierValueMaxTerm;
            this.MaxTermPeriod = maxTermPeriod;
            this.InterestRate = interestRate;
            this.InterestRateType = interestRateType;
            this.InterestFeesCharges = interestFeesCharges;
        }
        
        /// <summary>
        /// Gets or Sets AER
        /// </summary>
        [DataMember(Name="AER", EmitDefaultValue=false)]
        public string AER { get; set; }

        /// <summary>
        /// Gets or Sets Comments
        /// </summary>
        [DataMember(Name="comments", EmitDefaultValue=false)]
        public Comments Comments { get; set; }

        /// <summary>
        /// Уникальное определение диапазона уровней процентной ставки для кредита
        /// </summary>
        /// <value>Уникальное определение диапазона уровней процентной ставки для кредита</value>
        [DataMember(Name="identification", EmitDefaultValue=false)]
        public string Identification { get; set; }

        /// <summary>
        /// Валюта уровня
        /// </summary>
        /// <value>Валюта уровня</value>
        [DataMember(Name="tierCurrency", EmitDefaultValue=false)]
        public  TierCurrency { get; set; }

        /// <summary>
        /// Gets or Sets TierValueMinimum
        /// </summary>
        [DataMember(Name="tierValueMinimum", EmitDefaultValue=false)]
        public string TierValueMinimum { get; set; }

        /// <summary>
        /// Gets or Sets TierValueMaximum
        /// </summary>
        [DataMember(Name="tierValueMaximum", EmitDefaultValue=false)]
        public string TierValueMaximum { get; set; }

        /// <summary>
        /// Минимальный срок, на которой применяется уровень процентной ставки
        /// </summary>
        /// <value>Минимальный срок, на которой применяется уровень процентной ставки</value>
        [DataMember(Name="tierValueMinTerm", EmitDefaultValue=false)]
        public int? TierValueMinTerm { get; set; }

        /// <summary>
        /// Gets or Sets MinTermPeriod
        /// </summary>
        [DataMember(Name="minTermPeriod", EmitDefaultValue=false)]
        public PeriodUnit MinTermPeriod { get; set; }

        /// <summary>
        /// Максимальный срок, для которой применяется уровень процентной ставки
        /// </summary>
        /// <value>Максимальный срок, для которой применяется уровень процентной ставки</value>
        [DataMember(Name="tierValueMaxTerm", EmitDefaultValue=false)]
        public int? TierValueMaxTerm { get; set; }

        /// <summary>
        /// Gets or Sets MaxTermPeriod
        /// </summary>
        [DataMember(Name="maxTermPeriod", EmitDefaultValue=false)]
        public PeriodUnit MaxTermPeriod { get; set; }

        /// <summary>
        /// Gets or Sets InterestRate
        /// </summary>
        [DataMember(Name="interestRate", EmitDefaultValue=false)]
        public string InterestRate { get; set; }

        /// <summary>
        /// Gets or Sets InterestRateType
        /// </summary>
        [DataMember(Name="interestRateType", EmitDefaultValue=false)]
        public InterestRateType InterestRateType { get; set; }

        /// <summary>
        /// Информация о комиссиях и сборах
        /// </summary>
        /// <value>Информация о комиссиях и сборах</value>
        [DataMember(Name="InterestFeesCharges", EmitDefaultValue=false)]
        public List<InterestFeesCharges> InterestFeesCharges { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DebitInterestTierBand {\n");
            sb.Append("  AER: ").Append(AER).Append("\n");
            sb.Append("  Comments: ").Append(Comments).Append("\n");
            sb.Append("  Identification: ").Append(Identification).Append("\n");
            sb.Append("  TierCurrency: ").Append(TierCurrency).Append("\n");
            sb.Append("  TierValueMinimum: ").Append(TierValueMinimum).Append("\n");
            sb.Append("  TierValueMaximum: ").Append(TierValueMaximum).Append("\n");
            sb.Append("  TierValueMinTerm: ").Append(TierValueMinTerm).Append("\n");
            sb.Append("  MinTermPeriod: ").Append(MinTermPeriod).Append("\n");
            sb.Append("  TierValueMaxTerm: ").Append(TierValueMaxTerm).Append("\n");
            sb.Append("  MaxTermPeriod: ").Append(MaxTermPeriod).Append("\n");
            sb.Append("  InterestRate: ").Append(InterestRate).Append("\n");
            sb.Append("  InterestRateType: ").Append(InterestRateType).Append("\n");
            sb.Append("  InterestFeesCharges: ").Append(InterestFeesCharges).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DebitInterestTierBand);
        }

        /// <summary>
        /// Returns true if DebitInterestTierBand instances are equal
        /// </summary>
        /// <param name="input">Instance of DebitInterestTierBand to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DebitInterestTierBand input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AER == input.AER ||
                    (this.AER != null &&
                    this.AER.Equals(input.AER))
                ) && 
                (
                    this.Comments == input.Comments ||
                    (this.Comments != null &&
                    this.Comments.Equals(input.Comments))
                ) && 
                (
                    this.Identification == input.Identification ||
                    (this.Identification != null &&
                    this.Identification.Equals(input.Identification))
                ) && 
                (
                    this.TierCurrency == input.TierCurrency ||
                    (this.TierCurrency != null &&
                    this.TierCurrency.Equals(input.TierCurrency))
                ) && 
                (
                    this.TierValueMinimum == input.TierValueMinimum ||
                    (this.TierValueMinimum != null &&
                    this.TierValueMinimum.Equals(input.TierValueMinimum))
                ) && 
                (
                    this.TierValueMaximum == input.TierValueMaximum ||
                    (this.TierValueMaximum != null &&
                    this.TierValueMaximum.Equals(input.TierValueMaximum))
                ) && 
                (
                    this.TierValueMinTerm == input.TierValueMinTerm ||
                    (this.TierValueMinTerm != null &&
                    this.TierValueMinTerm.Equals(input.TierValueMinTerm))
                ) && 
                (
                    this.MinTermPeriod == input.MinTermPeriod ||
                    (this.MinTermPeriod != null &&
                    this.MinTermPeriod.Equals(input.MinTermPeriod))
                ) && 
                (
                    this.TierValueMaxTerm == input.TierValueMaxTerm ||
                    (this.TierValueMaxTerm != null &&
                    this.TierValueMaxTerm.Equals(input.TierValueMaxTerm))
                ) && 
                (
                    this.MaxTermPeriod == input.MaxTermPeriod ||
                    (this.MaxTermPeriod != null &&
                    this.MaxTermPeriod.Equals(input.MaxTermPeriod))
                ) && 
                (
                    this.InterestRate == input.InterestRate ||
                    (this.InterestRate != null &&
                    this.InterestRate.Equals(input.InterestRate))
                ) && 
                (
                    this.InterestRateType == input.InterestRateType ||
                    (this.InterestRateType != null &&
                    this.InterestRateType.Equals(input.InterestRateType))
                ) && 
                (
                    this.InterestFeesCharges == input.InterestFeesCharges ||
                    this.InterestFeesCharges != null &&
                    input.InterestFeesCharges != null &&
                    this.InterestFeesCharges.SequenceEqual(input.InterestFeesCharges)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AER != null)
                    hashCode = hashCode * 59 + this.AER.GetHashCode();
                if (this.Comments != null)
                    hashCode = hashCode * 59 + this.Comments.GetHashCode();
                if (this.Identification != null)
                    hashCode = hashCode * 59 + this.Identification.GetHashCode();
                if (this.TierCurrency != null)
                    hashCode = hashCode * 59 + this.TierCurrency.GetHashCode();
                if (this.TierValueMinimum != null)
                    hashCode = hashCode * 59 + this.TierValueMinimum.GetHashCode();
                if (this.TierValueMaximum != null)
                    hashCode = hashCode * 59 + this.TierValueMaximum.GetHashCode();
                if (this.TierValueMinTerm != null)
                    hashCode = hashCode * 59 + this.TierValueMinTerm.GetHashCode();
                if (this.MinTermPeriod != null)
                    hashCode = hashCode * 59 + this.MinTermPeriod.GetHashCode();
                if (this.TierValueMaxTerm != null)
                    hashCode = hashCode * 59 + this.TierValueMaxTerm.GetHashCode();
                if (this.MaxTermPeriod != null)
                    hashCode = hashCode * 59 + this.MaxTermPeriod.GetHashCode();
                if (this.InterestRate != null)
                    hashCode = hashCode * 59 + this.InterestRate.GetHashCode();
                if (this.InterestRateType != null)
                    hashCode = hashCode * 59 + this.InterestRateType.GetHashCode();
                if (this.InterestFeesCharges != null)
                    hashCode = hashCode * 59 + this.InterestFeesCharges.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
