/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Информация о доступности продукта и возможности доставки
    /// </summary>
    [DataContract]
        public partial class DeliveryRegions :  IEquatable<DeliveryRegions>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="DeliveryRegions" /> class.
        /// </summary>
        /// <param name="comments">comments.</param>
        /// <param name="deliveryRegionAndAddress">Информация о населенном пункте, где продукт доступен либо куда возможна доставка.</param>
        public DeliveryRegions(Comments comments = default(Comments), List<PostalAddressAndAdmZone> deliveryRegionAndAddress = default(List<PostalAddressAndAdmZone>))
        {
            this.Comments = comments;
            this.DeliveryRegionAndAddress = deliveryRegionAndAddress;
        }
        
        /// <summary>
        /// Gets or Sets Comments
        /// </summary>
        [DataMember(Name="comments", EmitDefaultValue=false)]
        public Comments Comments { get; set; }

        /// <summary>
        /// Информация о населенном пункте, где продукт доступен либо куда возможна доставка
        /// </summary>
        /// <value>Информация о населенном пункте, где продукт доступен либо куда возможна доставка</value>
        [DataMember(Name="DeliveryRegionAndAddress", EmitDefaultValue=false)]
        public List<PostalAddressAndAdmZone> DeliveryRegionAndAddress { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DeliveryRegions {\n");
            sb.Append("  Comments: ").Append(Comments).Append("\n");
            sb.Append("  DeliveryRegionAndAddress: ").Append(DeliveryRegionAndAddress).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DeliveryRegions);
        }

        /// <summary>
        /// Returns true if DeliveryRegions instances are equal
        /// </summary>
        /// <param name="input">Instance of DeliveryRegions to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DeliveryRegions input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Comments == input.Comments ||
                    (this.Comments != null &&
                    this.Comments.Equals(input.Comments))
                ) && 
                (
                    this.DeliveryRegionAndAddress == input.DeliveryRegionAndAddress ||
                    this.DeliveryRegionAndAddress != null &&
                    input.DeliveryRegionAndAddress != null &&
                    this.DeliveryRegionAndAddress.SequenceEqual(input.DeliveryRegionAndAddress)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Comments != null)
                    hashCode = hashCode * 59 + this.Comments.GetHashCode();
                if (this.DeliveryRegionAndAddress != null)
                    hashCode = hashCode * 59 + this.DeliveryRegionAndAddress.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
