/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Текущий статус оборудования.
    /// </summary>
    /// <value>Текущий статус оборудования.</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum DeviceCurrentStatusCode
    {
        /// <summary>
        /// Enum On for value: On | Доступно
        /// </summary>
        [EnumMember(Value = "On | Доступно")]
        On = 1,
        /// <summary>
        /// Enum Off for value: Off | Недоступно
        /// </summary>
        [EnumMember(Value = "Off | Недоступно")]
        Off = 2,
        /// <summary>
        /// Enum TempOff for value: TempOff | Временно недоступен
        /// </summary>
        [EnumMember(Value = "TempOff | Временно недоступен")]
        TempOff = 3    }
}
