/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Услуги доступные на оборудовании.
    /// </summary>
    /// <value>Услуги доступные на оборудовании.</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum DeviceServiceTypeCode
    {
        /// <summary>
        /// Enum CashWithdrawal for value: CashWithdrawal | Снятие наличных денежных средств
        /// </summary>
        [EnumMember(Value = "CashWithdrawal | Снятие наличных денежных средств")]
        CashWithdrawal = 1,
        /// <summary>
        /// Enum PINChange for value: PINChange | Смена ПИН
        /// </summary>
        [EnumMember(Value = "PINChange | Смена ПИН")]
        PINChange = 2,
        /// <summary>
        /// Enum PINUnblock for value: PINUnblock | Разблокировка ПИН
        /// </summary>
        [EnumMember(Value = "PINUnblock | Разблокировка ПИН")]
        PINUnblock = 3,
        /// <summary>
        /// Enum PINActivation for value: PINActivation | Активация ПИН
        /// </summary>
        [EnumMember(Value = "PINActivation | Активация ПИН")]
        PINActivation = 4,
        /// <summary>
        /// Enum Balance for value: Balance | Просмотр баланса
        /// </summary>
        [EnumMember(Value = "Balance | Просмотр баланса")]
        Balance = 5,
        /// <summary>
        /// Enum MiniStatement for value: MiniStatement | Выписка
        /// </summary>
        [EnumMember(Value = "MiniStatement | Выписка")]
        MiniStatement = 6,
        /// <summary>
        /// Enum BillPayments for value: BillPayments | Платежи
        /// </summary>
        [EnumMember(Value = "BillPayments | Платежи")]
        BillPayments = 7,
        /// <summary>
        /// Enum MobileBankingRegistration for value: MobileBankingRegistration | Регистрация мобильного банка
        /// </summary>
        [EnumMember(Value = "MobileBankingRegistration | Регистрация мобильного банка")]
        MobileBankingRegistration = 8,
        /// <summary>
        /// Enum CurrencyExhange for value: CurrencyExhange | Обмен валют
        /// </summary>
        [EnumMember(Value = "CurrencyExhange | Обмен валют")]
        CurrencyExhange = 9,
        /// <summary>
        /// Enum CashIn for value: CashIn | Пополнение наличными денежными средствами
        /// </summary>
        [EnumMember(Value = "CashIn | Пополнение наличными денежными средствами")]
        CashIn = 10,
        /// <summary>
        /// Enum Other for value: Other | Другие
        /// </summary>
        [EnumMember(Value = "Other | Другие")]
        Other = 11    }
}
