/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Типы комиссии
    /// </summary>
    /// <value>Типы комиссии</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum FeeTypeCode
    {
        /// <summary>
        /// Enum TransferOfFunds for value: transferOfFunds | при переводе денежных средств
        /// </summary>
        [EnumMember(Value = "transferOfFunds | при переводе денежных средств")]
        TransferOfFunds = 1,
        /// <summary>
        /// Enum WithdrawingMoneyFromAnATM for value: withdrawingMoneyFromAnATM | во время снятия в банкомате
        /// </summary>
        [EnumMember(Value = "withdrawingMoneyFromAnATM | во время снятия в банкомате")]
        WithdrawingMoneyFromAnATM = 2,
        /// <summary>
        /// Enum CountingBanknotes for value: countingBanknotes | при пересчете купюр
        /// </summary>
        [EnumMember(Value = "countingBanknotes | при пересчете купюр")]
        CountingBanknotes = 3,
        /// <summary>
        /// Enum CurrencyConversion for value: currencyConversion | во время конвертации валют
        /// </summary>
        [EnumMember(Value = "currencyConversion | во время конвертации валют")]
        CurrencyConversion = 4,
        /// <summary>
        /// Enum FactoringService for value: factoringService | за услугу факторинга
        /// </summary>
        [EnumMember(Value = "factoringService | за услугу факторинга")]
        FactoringService = 5,
        /// <summary>
        /// Enum IssuingLoans for value: issuingLoans | при выдаче кредитов
        /// </summary>
        [EnumMember(Value = "issuingLoans | при выдаче кредитов")]
        IssuingLoans = 6,
        /// <summary>
        /// Enum EarlyRepaymentOfTheLoan for value: earlyRepaymentOfTheLoan | по досрочному погашению
        /// </summary>
        [EnumMember(Value = "earlyRepaymentOfTheLoan | по досрочному погашению")]
        EarlyRepaymentOfTheLoan = 7,
        /// <summary>
        /// Enum ConsiderationOfAnApplicationForALoan for value: considerationOfAnApplicationForALoan | рассмотрения заявки на получение кредита
        /// </summary>
        [EnumMember(Value = "considerationOfAnApplicationForALoan | рассмотрения заявки на получение кредита")]
        ConsiderationOfAnApplicationForALoan = 8,
        /// <summary>
        /// Enum ConsultationsOnMortages for value: consultationsOnMortages | консультации по ипотекам
        /// </summary>
        [EnumMember(Value = "consultationsOnMortages | консультации по ипотекам")]
        ConsultationsOnMortages = 9,
        /// <summary>
        /// Enum ConsultationsOnInvesting for value: consultationsOnInvesting | консультации по ивестпродуктам
        /// </summary>
        [EnumMember(Value = "consultationsOnInvesting | консультации по ивестпродуктам")]
        ConsultationsOnInvesting = 10,
        /// <summary>
        /// Enum OpeningAccount for value: openingAccount | по открытию счета
        /// </summary>
        [EnumMember(Value = "openingAccount | по открытию счета")]
        OpeningAccount = 11,
        /// <summary>
        /// Enum SmsNotificating for value: smsNotificating | СМС оповещения
        /// </summary>
        [EnumMember(Value = "smsNotificating | СМС оповещения")]
        SmsNotificating = 12,
        /// <summary>
        /// Enum OmmissionBroker for value: сommissionBroker | Вознаграждение Брокера за исполнение Приказов Клиента на фондовом рынке
        /// </summary>
        [EnumMember(Value = "сommissionBroker | Вознаграждение Брокера за исполнение Приказов Клиента на фондовом рынке")]
        OmmissionBroker = 13,
        /// <summary>
        /// Enum MarginLending for value: marginLending | При маржинальном кредитовании и переносе непокрытых позиций Клиента
        /// </summary>
        [EnumMember(Value = "marginLending | При маржинальном кредитовании и переносе непокрытых позиций Клиента")]
        MarginLending = 14    }
}
