/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Локация объекта в географических координатах
    /// </summary>
    [DataContract]
        public partial class Geolocation :  IEquatable<Geolocation>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Geolocation" /> class.
        /// </summary>
        /// <param name="geographicCoordinates">geographicCoordinates (required).</param>
        public Geolocation(GeographicCoordinates geographicCoordinates = default(GeographicCoordinates))
        {
            // to ensure "geographicCoordinates" is required (not null)
            if (geographicCoordinates == null)
            {
                throw new InvalidDataException("geographicCoordinates is a required property for Geolocation and cannot be null");
            }
            else
            {
                this.GeographicCoordinates = geographicCoordinates;
            }
        }
        
        /// <summary>
        /// Gets or Sets GeographicCoordinates
        /// </summary>
        [DataMember(Name="GeographicCoordinates", EmitDefaultValue=false)]
        public GeographicCoordinates GeographicCoordinates { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Geolocation {\n");
            sb.Append("  GeographicCoordinates: ").Append(GeographicCoordinates).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Geolocation);
        }

        /// <summary>
        /// Returns true if Geolocation instances are equal
        /// </summary>
        /// <param name="input">Instance of Geolocation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Geolocation input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.GeographicCoordinates == input.GeographicCoordinates ||
                    (this.GeographicCoordinates != null &&
                    this.GeographicCoordinates.Equals(input.GeographicCoordinates))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.GeographicCoordinates != null)
                    hashCode = hashCode * 59 + this.GeographicCoordinates.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
