/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Варианты начисления процентов (капитализация)
    /// </summary>
    /// <value>Варианты начисления процентов (капитализация)</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum InterestCalculationMethod
    {
        /// <summary>
        /// Enum SimpleInterest for value: SimpleInterest | Простые проценты
        /// </summary>
        [EnumMember(Value = "SimpleInterest | Простые проценты")]
        SimpleInterest = 1,
        /// <summary>
        /// Enum Compound for value: Compound | Сложные проценты
        /// </summary>
        [EnumMember(Value = "Compound | Сложные проценты")]
        Compound = 2    }
}
