/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Комиссии за овердрафт
    /// </summary>
    /// <value>Комиссии за овердрафт</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum OverdraftFeeType
    {
        /// <summary>
        /// Enum ConnectingOverdraft for value: connectingOverdraft | Подключение овердрафта
        /// </summary>
        [EnumMember(Value = "connectingOverdraft | Подключение овердрафта")]
        ConnectingOverdraft = 1,
        /// <summary>
        /// Enum ExtensionOverdraft for value: extensionOverdraft | Продление овердрафта
        /// </summary>
        [EnumMember(Value = "extensionOverdraft | Продление овердрафта")]
        ExtensionOverdraft = 2,
        /// <summary>
        /// Enum UnauthorizedOverdraft for value: unauthorizedOverdraft | Технический (несанкционированный) овердрафт
        /// </summary>
        [EnumMember(Value = "unauthorizedOverdraft | Технический (несанкционированный) овердрафт")]
        UnauthorizedOverdraft = 3    }
}
