/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Подробная информация о процентных ставках по овердрафту
    /// </summary>
    [DataContract]
        public partial class Overdraft :  IEquatable<Overdraft>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Overdraft" /> class.
        /// </summary>
        /// <param name="comments">comments.</param>
        /// <param name="overdraftTierBandSet">Подробная информация о процентных ставках по овердрафту (required).</param>
        public Overdraft(Comments comments = default(Comments), List<OverdraftTierBandSet> overdraftTierBandSet = default(List<OverdraftTierBandSet>))
        {
            // to ensure "overdraftTierBandSet" is required (not null)
            if (overdraftTierBandSet == null)
            {
                throw new InvalidDataException("overdraftTierBandSet is a required property for Overdraft and cannot be null");
            }
            else
            {
                this.OverdraftTierBandSet = overdraftTierBandSet;
            }
            this.Comments = comments;
        }
        
        /// <summary>
        /// Gets or Sets Comments
        /// </summary>
        [DataMember(Name="comments", EmitDefaultValue=false)]
        public Comments Comments { get; set; }

        /// <summary>
        /// Подробная информация о процентных ставках по овердрафту
        /// </summary>
        /// <value>Подробная информация о процентных ставках по овердрафту</value>
        [DataMember(Name="OverdraftTierBandSet", EmitDefaultValue=false)]
        public List<OverdraftTierBandSet> OverdraftTierBandSet { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Overdraft {\n");
            sb.Append("  Comments: ").Append(Comments).Append("\n");
            sb.Append("  OverdraftTierBandSet: ").Append(OverdraftTierBandSet).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Overdraft);
        }

        /// <summary>
        /// Returns true if Overdraft instances are equal
        /// </summary>
        /// <param name="input">Instance of Overdraft to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Overdraft input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Comments == input.Comments ||
                    (this.Comments != null &&
                    this.Comments.Equals(input.Comments))
                ) && 
                (
                    this.OverdraftTierBandSet == input.OverdraftTierBandSet ||
                    this.OverdraftTierBandSet != null &&
                    input.OverdraftTierBandSet != null &&
                    this.OverdraftTierBandSet.SequenceEqual(input.OverdraftTierBandSet)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Comments != null)
                    hashCode = hashCode * 59 + this.Comments.GetHashCode();
                if (this.OverdraftTierBandSet != null)
                    hashCode = hashCode * 59 + this.OverdraftTierBandSet.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
