/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Схема идентификации юридического или физического лица
    /// </summary>
    /// <value>Схема идентификации юридического или физического лица</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum PartyIdentificationCode
    {
        /// <summary>
        /// Enum TXID for value: RU.CBR.TXID | Идентификационный номер налогоплательщика (ИНН)
        /// </summary>
        [EnumMember(Value = "RU.CBR.TXID | Идентификационный номер налогоплательщика (ИНН)")]
        TXID = 1,
        /// <summary>
        /// Enum OGRN for value: RU.CBR.OGRN | Основной государственный регистрационный номер (ОГРН)
        /// </summary>
        [EnumMember(Value = "RU.CBR.OGRN | Основной государственный регистрационный номер (ОГРН)")]
        OGRN = 2    }
}
