/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Информация о возможности выбора клиентом даты платежа
    /// </summary>
    [DataContract]
        public partial class PaymentDate :  IEquatable<PaymentDate>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentDate" /> class.
        /// </summary>
        /// <param name="customerChoice">Возможность выбрать дату платежа | FALSE – дата платежа назначается организацией;  TRUE – дату платежа выбирает клиент.</param>
        /// <param name="comments">comments.</param>
        public PaymentDate(bool? customerChoice = default(bool?), Comments comments = default(Comments))
        {
            this.CustomerChoice = customerChoice;
            this.Comments = comments;
        }
        
        /// <summary>
        /// Возможность выбрать дату платежа | FALSE – дата платежа назначается организацией;  TRUE – дату платежа выбирает клиент
        /// </summary>
        /// <value>Возможность выбрать дату платежа | FALSE – дата платежа назначается организацией;  TRUE – дату платежа выбирает клиент</value>
        [DataMember(Name="customerChoice", EmitDefaultValue=false)]
        public bool? CustomerChoice { get; set; }

        /// <summary>
        /// Gets or Sets Comments
        /// </summary>
        [DataMember(Name="comments", EmitDefaultValue=false)]
        public Comments Comments { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaymentDate {\n");
            sb.Append("  CustomerChoice: ").Append(CustomerChoice).Append("\n");
            sb.Append("  Comments: ").Append(Comments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PaymentDate);
        }

        /// <summary>
        /// Returns true if PaymentDate instances are equal
        /// </summary>
        /// <param name="input">Instance of PaymentDate to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaymentDate input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CustomerChoice == input.CustomerChoice ||
                    (this.CustomerChoice != null &&
                    this.CustomerChoice.Equals(input.CustomerChoice))
                ) && 
                (
                    this.Comments == input.Comments ||
                    (this.Comments != null &&
                    this.Comments.Equals(input.Comments))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CustomerChoice != null)
                    hashCode = hashCode * 59 + this.CustomerChoice.GetHashCode();
                if (this.Comments != null)
                    hashCode = hashCode * 59 + this.Comments.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
