/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Единица измерения периода
    /// </summary>
    /// <value>Единица измерения периода</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum PeriodUnit
    {
        /// <summary>
        /// Enum Hour for value: Hour | Час
        /// </summary>
        [EnumMember(Value = "Hour | Час")]
        Hour = 1,
        /// <summary>
        /// Enum Day for value: Day | День
        /// </summary>
        [EnumMember(Value = "Day | День")]
        Day = 2,
        /// <summary>
        /// Enum Week for value: Week | Неделя
        /// </summary>
        [EnumMember(Value = "Week | Неделя")]
        Week = 3,
        /// <summary>
        /// Enum Month for value: Month | Месяц
        /// </summary>
        [EnumMember(Value = "Month | Месяц")]
        Month = 4,
        /// <summary>
        /// Enum Quarter for value: Quarter | Квартал
        /// </summary>
        [EnumMember(Value = "Quarter | Квартал")]
        Quarter = 5,
        /// <summary>
        /// Enum HalfYear for value: HalfYear | Полугодие
        /// </summary>
        [EnumMember(Value = "HalfYear | Полугодие")]
        HalfYear = 6,
        /// <summary>
        /// Enum Year for value: Year | Год
        /// </summary>
        [EnumMember(Value = "Year | Год")]
        Year = 7,
        /// <summary>
        /// Enum AcademicTerm for value: AcademicTerm | Академическая единица
        /// </summary>
        [EnumMember(Value = "AcademicTerm | Академическая единица")]
        AcademicTerm = 8    }
}
