/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Тип продукта
    /// </summary>
    /// <value>Тип продукта</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum ProductType
    {
        /// <summary>
        /// Enum DepositIndividual for value: depositIndividual | Депозит физического лица
        /// </summary>
        [EnumMember(Value = "depositIndividual | Депозит физического лица")]
        DepositIndividual = 1,
        /// <summary>
        /// Enum DepositlegalEntity for value: depositlegalEntity | Депозит юридического лица
        /// </summary>
        [EnumMember(Value = "depositlegalEntity | Депозит юридического лица")]
        DepositlegalEntity = 2,
        /// <summary>
        /// Enum CAindividual for value: CAindividual | Текущий счет физического лица
        /// </summary>
        [EnumMember(Value = "CAindividual | Текущий счет физического лица")]
        CAindividual = 3,
        /// <summary>
        /// Enum CALegalEntity for value: CALegalEntity | Расчетный счет юридического лица
        /// </summary>
        [EnumMember(Value = "CALegalEntity | Расчетный счет юридического лица")]
        CALegalEntity = 4,
        /// <summary>
        /// Enum DebitCard for value: debitCard | Дебетовая карта
        /// </summary>
        [EnumMember(Value = "debitCard | Дебетовая карта")]
        DebitCard = 5,
        /// <summary>
        /// Enum CreditCard for value: creditCard | Кредитная карта
        /// </summary>
        [EnumMember(Value = "creditCard | Кредитная карта")]
        CreditCard = 6,
        /// <summary>
        /// Enum LoanCar for value: loanCar | Автокредит
        /// </summary>
        [EnumMember(Value = "loanCar | Автокредит")]
        LoanCar = 7,
        /// <summary>
        /// Enum LoanIndividual for value: loanIndividual | Кредит физическому лицу
        /// </summary>
        [EnumMember(Value = "loanIndividual | Кредит физическому лицу")]
        LoanIndividual = 8,
        /// <summary>
        /// Enum LoanLegalEntity for value: loanLegalEntity | Кредит юридического лица
        /// </summary>
        [EnumMember(Value = "loanLegalEntity | Кредит юридического лица")]
        LoanLegalEntity = 9,
        /// <summary>
        /// Enum Mortage for value: mortage | Ипотека
        /// </summary>
        [EnumMember(Value = "mortage | Ипотека")]
        Mortage = 10,
        /// <summary>
        /// Enum Investment for value: investment | Инвестиционный продукт
        /// </summary>
        [EnumMember(Value = "investment | Инвестиционный продукт")]
        Investment = 11,
        /// <summary>
        /// Enum Other for value: Other | Другой продукт
        /// </summary>
        [EnumMember(Value = "Other | Другой продукт")]
        Other = 12    }
}
