/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Схема погашения кредитного продукта (Аннуитет, Платежи равными долями, Дифференцированный платеж)
    /// </summary>
    /// <value>Схема погашения кредитного продукта (Аннуитет, Платежи равными долями, Дифференцированный платеж)</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum RepaymentTypeCode
    {
        /// <summary>
        /// Enum FixedCapitalFullyAmortising for value: FixedCapitalFullyAmortising | Фиксированная сумма платежа, полностью выплачивающая переменное разделение капитала и процентов до даты погашения.
        /// </summary>
        [EnumMember(Value = "FixedCapitalFullyAmortising | Фиксированная сумма платежа, полностью выплачивающая переменное разделение капитала и процентов до даты погашения.")]
        FixedCapitalFullyAmortising = 1,
        /// <summary>
        /// Enum Balloon for value: Balloon | Погашение, при котором только часть основного остатка по кредитам амортизируется в течение срока, оставшийся остаток подлежит погашению в конце срока
        /// </summary>
        [EnumMember(Value = "Balloon | Погашение, при котором только часть основного остатка по кредитам амортизируется в течение срока, оставшийся остаток подлежит погашению в конце срока")]
        Balloon = 2,
        /// <summary>
        /// Enum Bullet for value: Bullet | Погашение, при котором вся сумма кредита выплачивается при наступлении срока погашения
        /// </summary>
        [EnumMember(Value = "Bullet | Погашение, при котором вся сумма кредита выплачивается при наступлении срока погашения")]
        Bullet = 3,
        /// <summary>
        /// Enum CapitalAndInterest for value: CapitalAndInterest | Погашение капитала и процентов, при котором кредит полностью амортизируется в течение срока платежа
        /// </summary>
        [EnumMember(Value = "CapitalAndInterest | Погашение капитала и процентов, при котором кредит полностью амортизируется в течение срока платежа")]
        CapitalAndInterest = 4,
        /// <summary>
        /// Enum CustomSchedule for value: CustomSchedule | Погашение определяется пользователем в индивидуальные сроки и не обязательно является периодическим
        /// </summary>
        [EnumMember(Value = "CustomSchedule | Погашение определяется пользователем в индивидуальные сроки и не обязательно является периодическим")]
        CustomSchedule = 5,
        /// <summary>
        /// Enum EarlyRepayment for value: EarlyRepayment | Досрочное погашение полной суммы кредита до согласованного срока погашения
        /// </summary>
        [EnumMember(Value = "EarlyRepayment | Досрочное погашение полной суммы кредита до согласованного срока погашения")]
        EarlyRepayment = 6,
        /// <summary>
        /// Enum FixedCapitalWithBullet for value: FixedCapitalWithBullet | Фиксированная сумма платежа с переменным разделением капитала и процентов с последним погашением остатка в конце.
        /// </summary>
        [EnumMember(Value = "FixedCapitalWithBullet | Фиксированная сумма платежа с переменным разделением капитала и процентов с последним погашением остатка в конце.")]
        FixedCapitalWithBullet = 7,
        /// <summary>
        /// Enum FixedCapitalAndInterestReducingBalance for value: FixedCapitalAndInterestReducingBalance | Фиксированная сумма платежа с разделением капитала и процентов в определенное время. В конце может остаться сумма для погашения.
        /// </summary>
        [EnumMember(Value = "FixedCapitalAndInterestReducingBalance | Фиксированная сумма платежа с разделением капитала и процентов в определенное время. В конце может остаться сумма для погашения.")]
        FixedCapitalAndInterestReducingBalance = 8,
        /// <summary>
        /// Enum InterestOnly for value: InterestOnly | Переменная сумма платежа с выплатой процентов только по кредиту с последним погашением в конце.
        /// </summary>
        [EnumMember(Value = "InterestOnly | Переменная сумма платежа с выплатой процентов только по кредиту с последним погашением в конце.")]
        InterestOnly = 9,
        /// <summary>
        /// Enum Other for value: Other  | Другой тип погашения
        /// </summary>
        [EnumMember(Value = "Other  | Другой тип погашения")]
        Other = 10,
        /// <summary>
        /// Enum PrepaymentFee for value: PrepaymentFee | Переплата или возврат
        /// </summary>
        [EnumMember(Value = "PrepaymentFee | Переплата или возврат")]
        PrepaymentFee = 11,
        /// <summary>
        /// Enum RepaymentWithBullet for value: RepaymentWithBullet | Периодическое погашение с выплатой комбинации капитала и процентов с последним погашением в конце.
        /// </summary>
        [EnumMember(Value = "RepaymentWithBullet | Периодическое погашение с выплатой комбинации капитала и процентов с последним погашением в конце.")]
        RepaymentWithBullet = 12,
        /// <summary>
        /// Enum StraightLineInterestOnly for value: StraightLineInterestOnly | Переменная сумма платежа, выплачивающая фиксированную процентную ставку по ссудес последним погашением в конце.
        /// </summary>
        [EnumMember(Value = "StraightLineInterestOnly | Переменная сумма платежа, выплачивающая фиксированную процентную ставку по ссудес последним погашением в конце.")]
        StraightLineInterestOnly = 13    }
}
