/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Сегмент клиентов
    /// </summary>
    /// <value>Сегмент клиентов</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum SegmentCode
    {
        /// <summary>
        /// Enum Business for value: Business | Юридические лица, индивидуальные предприниматели и лица занимающиеся частной практикой
        /// </summary>
        [EnumMember(Value = "Business | Юридические лица, индивидуальные предприниматели и лица занимающиеся частной практикой")]
        Business = 1,
        /// <summary>
        /// Enum Individual for value: Individual | Физические лица
        /// </summary>
        [EnumMember(Value = "Individual | Физические лица")]
        Individual = 2    }
}
