/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Доступные услуги
    /// </summary>
    /// <value>Доступные услуги</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum ServiceTypeCode
    {
        /// <summary>
        /// Enum Loan for value: Loan | Кредит
        /// </summary>
        [EnumMember(Value = "Loan | Кредит")]
        Loan = 1,
        /// <summary>
        /// Enum Deposit for value: Deposit | Депозит
        /// </summary>
        [EnumMember(Value = "Deposit | Депозит")]
        Deposit = 2,
        /// <summary>
        /// Enum Card for value: Card | Карта
        /// </summary>
        [EnumMember(Value = "Card | Карта")]
        Card = 3,
        /// <summary>
        /// Enum Transfer for value: Transfer | Денежный перевод
        /// </summary>
        [EnumMember(Value = "Transfer | Денежный перевод")]
        Transfer = 4,
        /// <summary>
        /// Enum Jewel for value: Jewel | Драгоценности
        /// </summary>
        [EnumMember(Value = "Jewel | Драгоценности")]
        Jewel = 5,
        /// <summary>
        /// Enum CurrencyExchange for value: CurrencyExchange | Обмен валют
        /// </summary>
        [EnumMember(Value = "CurrencyExchange | Обмен валют")]
        CurrencyExchange = 6,
        /// <summary>
        /// Enum DirectDebit for value: DirectDebit | Прямое дебетование
        /// </summary>
        [EnumMember(Value = "DirectDebit | Прямое дебетование")]
        DirectDebit = 7,
        /// <summary>
        /// Enum Other for value: Other | Другая услуга
        /// </summary>
        [EnumMember(Value = "Other | Другая услуга")]
        Other = 8    }
}
