/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Контакты в социальных сетях
    /// </summary>
    [DataContract]
        public partial class SocialNetworks :  IEquatable<SocialNetworks>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SocialNetworks" /> class.
        /// </summary>
        /// <param name="networkName">networkName (required).</param>
        /// <param name="url">URL-адрес для социальной сети/мессенджера (required).</param>
        /// <param name="description">Дополнительная информация в свободной форме.</param>
        public SocialNetworks(SocialNetworkNameCode networkName = default(SocialNetworkNameCode), string url = default(string), string description = default(string))
        {
            // to ensure "networkName" is required (not null)
            if (networkName == null)
            {
                throw new InvalidDataException("networkName is a required property for SocialNetworks and cannot be null");
            }
            else
            {
                this.NetworkName = networkName;
            }
            // to ensure "url" is required (not null)
            if (url == null)
            {
                throw new InvalidDataException("url is a required property for SocialNetworks and cannot be null");
            }
            else
            {
                this.Url = url;
            }
            this.Description = description;
        }
        
        /// <summary>
        /// Gets or Sets NetworkName
        /// </summary>
        [DataMember(Name="networkName", EmitDefaultValue=false)]
        public SocialNetworkNameCode NetworkName { get; set; }

        /// <summary>
        /// URL-адрес для социальной сети/мессенджера
        /// </summary>
        /// <value>URL-адрес для социальной сети/мессенджера</value>
        [DataMember(Name="url", EmitDefaultValue=false)]
        public string Url { get; set; }

        /// <summary>
        /// Дополнительная информация в свободной форме
        /// </summary>
        /// <value>Дополнительная информация в свободной форме</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SocialNetworks {\n");
            sb.Append("  NetworkName: ").Append(NetworkName).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SocialNetworks);
        }

        /// <summary>
        /// Returns true if SocialNetworks instances are equal
        /// </summary>
        /// <param name="input">Instance of SocialNetworks to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SocialNetworks input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.NetworkName == input.NetworkName ||
                    (this.NetworkName != null &&
                    this.NetworkName.Equals(input.NetworkName))
                ) && 
                (
                    this.Url == input.Url ||
                    (this.Url != null &&
                    this.Url.Equals(input.Url))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.NetworkName != null)
                    hashCode = hashCode * 59 + this.NetworkName.GetHashCode();
                if (this.Url != null)
                    hashCode = hashCode * 59 + this.Url.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
