/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Название социальной сети/мессенджера
    /// </summary>
    /// <value>Название социальной сети/мессенджера</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum SocialNetworkNameCode
    {
        /// <summary>
        /// Enum VK for value: VK | ВКонтакте
        /// </summary>
        [EnumMember(Value = "VK | ВКонтакте")]
        VK = 1,
        /// <summary>
        /// Enum FacebookFacebook for value: Facebook | Facebook
        /// </summary>
        [EnumMember(Value = "Facebook | Facebook")]
        FacebookFacebook = 2,
        /// <summary>
        /// Enum OK for value: OK | Одноклассники
        /// </summary>
        [EnumMember(Value = "OK | Одноклассники")]
        OK = 3,
        /// <summary>
        /// Enum InstagramInstagram for value: Instagram | Instagram
        /// </summary>
        [EnumMember(Value = "Instagram | Instagram")]
        InstagramInstagram = 4,
        /// <summary>
        /// Enum TwitterTwitter for value: Twitter | Twitter
        /// </summary>
        [EnumMember(Value = "Twitter | Twitter")]
        TwitterTwitter = 5,
        /// <summary>
        /// Enum MessengerMessenger for value: Messenger | Messenger
        /// </summary>
        [EnumMember(Value = "Messenger | Messenger")]
        MessengerMessenger = 6,
        /// <summary>
        /// Enum IMessageiMessage for value: iMessage | iMessage
        /// </summary>
        [EnumMember(Value = "iMessage | iMessage")]
        IMessageiMessage = 7,
        /// <summary>
        /// Enum ViberViber for value: Viber | Viber
        /// </summary>
        [EnumMember(Value = "Viber | Viber")]
        ViberViber = 8,
        /// <summary>
        /// Enum WhatsAppWhatsApp for value: WhatsApp | WhatsApp
        /// </summary>
        [EnumMember(Value = "WhatsApp | WhatsApp")]
        WhatsAppWhatsApp = 9,
        /// <summary>
        /// Enum Telegram for value: Telegram | Телеграм
        /// </summary>
        [EnumMember(Value = "Telegram | Телеграм")]
        Telegram = 10    }
}
