/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Описывает, подлежат ли начисленные проценты зачислению на текущий счет или должны быть начислены на другой банковский счет.
    /// </summary>
    /// <value>Описывает, подлежат ли начисленные проценты зачислению на текущий счет или должны быть начислены на другой банковский счет.</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum TierBandMethodDestination
    {
        /// <summary>
        /// Enum CurrentAccount for value: CurrentAccount | на текущий счет
        /// </summary>
        [EnumMember(Value = "CurrentAccount | на текущий счет")]
        CurrentAccount = 1,
        /// <summary>
        /// Enum AnotherAccount for value: AnotherAccount | на другой счет
        /// </summary>
        [EnumMember(Value = "AnotherAccount | на другой счет")]
        AnotherAccount = 2    }
}
