/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Виды процентной ставки.
    /// </summary>
    /// <value>Виды процентной ставки.</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum TierBandMethod
    {
        /// <summary>
        /// Enum Floated for value: Floated | Плавающая процентная ставка, подлежит периодическому пересмотру по мере изменения остатка / задолженности
        /// </summary>
        [EnumMember(Value = "Floated | Плавающая процентная ставка, подлежит периодическому пересмотру по мере изменения остатка / задолженности")]
        Floated = 1,
        /// <summary>
        /// Enum Tiered for value: Tiered | Многоуровневая процентная ставка, определяет фиксированное значения процентов для определенного уровня / диапазона остатка / задолженности
        /// </summary>
        [EnumMember(Value = "Tiered | Многоуровневая процентная ставка, определяет фиксированное значения процентов для определенного уровня / диапазона остатка / задолженности")]
        Tiered = 2,
        /// <summary>
        /// Enum Fixed for value: Fixed | Фиксированная процентная ставка, подразумевает неизменную на протяжении всего периода соглашения процентную величину
        /// </summary>
        [EnumMember(Value = "Fixed | Фиксированная процентная ставка, подразумевает неизменную на протяжении всего периода соглашения процентную величину")]
        Fixed = 3    }
}
