/* 
 * Получение публичной информации о банковских продуктах
 *
 * Содержит описываются API для Открытых банковских интерфейсов для получения публичной информации о банковских продуктах.
 *
 * OpenAPI spec version: 1.3.1
 * Contact: info@fintechru.org
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Тип транспортного средства
    /// </summary>
    /// <value>Тип транспортного средства</value>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum TypesTransport
    {
        /// <summary>
        /// Enum Car for value: Car | Легковой автомобиль
        /// </summary>
        [EnumMember(Value = "Car | Легковой автомобиль")]
        Car = 1,
        /// <summary>
        /// Enum Truck for value: Truck | Грузовой автомобиль
        /// </summary>
        [EnumMember(Value = "Truck | Грузовой автомобиль")]
        Truck = 2,
        /// <summary>
        /// Enum Bus for value: Bus | Автобус
        /// </summary>
        [EnumMember(Value = "Bus | Автобус")]
        Bus = 3,
        /// <summary>
        /// Enum Mototechnics for value: Mototechnics | Мототехника
        /// </summary>
        [EnumMember(Value = "Mototechnics | Мототехника")]
        Mototechnics = 4,
        /// <summary>
        /// Enum Boatsandyachts for value: Boats and yachts | Катера и яхты
        /// </summary>
        [EnumMember(Value = "Boats and yachts | Катера и яхты")]
        Boatsandyachts = 5,
        /// <summary>
        /// Enum Snowmobiles for value: Snowmobiles | Снегоходы
        /// </summary>
        [EnumMember(Value = "Snowmobiles | Снегоходы")]
        Snowmobiles = 6,
        /// <summary>
        /// Enum Other for value: Other | Другие транспортные стредства
        /// </summary>
        [EnumMember(Value = "Other | Другие транспортные стредства")]
        Other = 7    }
}
